{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jdra.igor",
    "module": "user-client",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-client-1.0.1.jar",
          "url": "user-client-1.0.1.jar",
          "size": 1201,
          "sha512": "dd548683b72bf968f0bd704ee0083980fae9700eb7c31852a4eeb2a57afe1ffe775b08b08e2afeb5ff2bda8de71b317a5d13e2b3c38130a0064bbbcb2fbfad9b",
          "sha256": "3b8ec9bb7ba9e99386c4af5d130846bab944675e9fb867c2f412f70a7eb84ee6",
          "sha1": "20466898cfc5fa1fa282d01b2a2de3c640d6aebf",
          "md5": "b9225b8728204d8b07a27eb5303000e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "user-client-1.0.1.jar",
          "url": "user-client-1.0.1.jar",
          "size": 1201,
          "sha512": "dd548683b72bf968f0bd704ee0083980fae9700eb7c31852a4eeb2a57afe1ffe775b08b08e2afeb5ff2bda8de71b317a5d13e2b3c38130a0064bbbcb2fbfad9b",
          "sha256": "3b8ec9bb7ba9e99386c4af5d130846bab944675e9fb867c2f412f70a7eb84ee6",
          "sha1": "20466898cfc5fa1fa282d01b2a2de3c640d6aebf",
          "md5": "b9225b8728204d8b07a27eb5303000e7"
        }
      ]
    }
  ]
}
